program: sweeper2.0.py
method: random
name: sweepmania_cnn3d_dx_final
project: data001_train_randComb_huge1000_v2e_thres15_final_adClearSep0.1-1.0_size2x7221_cnn3d
parameters:
    batch_size: 
        values: [16,64]
    lr: 
        values: [0.0001]
    optimizer: 
        values: [RMSprop]
    epochs: 
        values: [500]
    repetition: 
        values: [01, 02]
    nn:
        value: cnn3d
