program: sweeper2.0.py
method: random
name: sweepmania_mlp_save_01
project: data001_train_randComb_huge1000_v2e_thres15_final_adClearSep0.1-1.0_size2x7221_mlp
parameters:
    batch_size: 
        values: [256,512,1024,2048,3072]
    hidden_size: 
        values: [32]
    lr: 
        values: [0.00005,0.0001,0.0005,0.001,0.003]
    optimizer: 
        values: [Adam, RMSprop]
    epochs: 
        values: [400]
    repetition: 
        values: [01, 02]
    nn:
        value: mlp
